workspace: FormatterKit.xcworkspace
xcodeproj: Example/FormatterKit Example.xcodeproj
build_directory: build/slather
source_directory: FormatterKit
binary_file: build/slather/FormatterKit.framework/FormatterKit
ignore:
  - ../**
