workspace: FormatterKit.xcworkspace
xcodeproj: Example/FormatterKit Example.xcodeproj
build_directory: build/slather
source_directory: FormatterKit
binary_file: build/DerivedData/English/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/FormatterKit.framework/FormatterKit
ignore:
  - ../**
